# Generated by Django 5.1.5 on 2025-03-21 15:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageProduct',
            fields=[
                ('damage_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('quantity_damaged', models.IntegerField()),
                ('damage_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('employee_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemWarranty',
            fields=[
                ('order_item_warranty_id', models.AutoField(primary_key=True, serialize=False)),
                ('warranty_start_date', models.DateTimeField()),
                ('warranty_end_date', models.DateTimeField()),
                ('warranty_use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWarranty',
            fields=[
                ('product_warranty_id', models.AutoField(primary_key=True, serialize=False)),
                ('warranty_start_date', models.DateTimeField()),
                ('warranty_end_date', models.DateTimeField()),
                ('warranty_use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(max_length=255)),
                ('supplier_contact_number', models.CharField(max_length=50)),
                ('supplier_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(default='Employee', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_status', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('quantity_received', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('stock_status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('old_item', models.BooleanField(default=False)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.damageproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetails',
            fields=[
                ('order_item_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('order_item_warranty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.orderitemwarranty')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('order_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderpayment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_point', models.IntegerField()),
                ('warranty_duration', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order_status', models.CharField(max_length=50)),
                ('expected_delivery_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('po_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('product_warranty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productwarranty')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('purchase_order_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('expense_type', models.CharField(max_length=100)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorderpayment')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_update', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModule',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expenses')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.income')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('replacement_id', models.AutoField(primary_key=True, serialize=False)),
                ('replacement_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('new_item', models.BooleanField(default=False)),
                ('return_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.return')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(max_length=50)),
                ('return_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.return')),
            ],
        ),
    ]
