# Generated by Django 5.1.7 on 2025-05-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='employee',
        ),
    ]
