# Generated by Django 4.2 on 2025-03-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('account_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('customer_type', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('email', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('quantity_damaged', models.IntegerField()),
                ('damage_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('employee_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('expense_type', models.TextField()),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.TextField()),
                ('payment_method', models.TextField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('quantity_received', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('stock_status', models.TextField()),
                ('location', models.TextField()),
                ('serial_number', models.TextField(unique=True)),
                ('old_item', models.BooleanField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.damageproduct')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('warranty_use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_point', models.IntegerField()),
                ('warranty_duration', models.TextField()),
                ('model', models.TextField()),
                ('brand', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('warranty_use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.TextField()),
                ('expected_delivery_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.product')),
                ('product_warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.productwarranty')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.TextField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('new_item', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.TextField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.expenses')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.income')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('status', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('contact_number', models.TextField()),
                ('email', models.TextField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TouristSpot',
        ),
        migrations.AddField(
            model_name='replacement',
            name='return_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.returns'),
        ),
        migrations.AddField(
            model_name='refund',
            name='return_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.returns'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.productcategory'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.orders'),
        ),
        migrations.AddField(
            model_name='orderitemdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.orders'),
        ),
        migrations.AddField(
            model_name='orderitemdetails',
            name='warranty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.orderitemwarranty'),
        ),
        migrations.AddField(
            model_name='income',
            name='order_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.orderpayment'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='purchase_order_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.purchaseorderpayment'),
        ),
        migrations.AddField(
            model_name='account',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.employee'),
        ),
    ]
