# Generated by Django 5.1.7 on 2025-05-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0002_remove_account_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='sia.employee'),
        ),
    ]
