# Generated by Django 5.1.7 on 2025-04-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0002_account_customer_damageproduct_employee_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sia.product'),
            preserve_default=False,
        ),
    ]
