# Generated by Django 5.1.7 on 2025-04-28 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0003_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageproduct',
            name='damage_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='damage_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_inventory', to='sia.damageproduct'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='sia.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_duration',
            field=models.CharField(max_length=100),
        ),
    ]
