# Generated by Django 5.1.7 on 2025-05-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0003_account_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageproduct',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.inventory'),
        ),
    ]
