# Generated by Django 5.0.6 on 2025-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0004_alter_damageproduct_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='catalog',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='sia.product'),
        ),
    ]
