# Generated by Django 5.1.7 on 2025-04-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0005_alter_product_category_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageproduct',
            name='inventory_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='sia.inventory'),
            preserve_default=False,
        ),
    ]
