# Generated by Django 5.0.6 on 2025-05-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0006_account_accessible_pages_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
