# Generated by Django 4.2 on 2025-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0006_account_accessible_pages_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
