# Generated by Django 5.1.7 on 2025-05-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0006_damageproduct_inventory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='sia.employee'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.TextField(default='Active'),
        ),
    ]
