# Generated by Django 5.0.6 on 2025-05-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0007_remove_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sia.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accessible_pages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.TextField(default='Active'),
        ),
    ]
