# Generated by Django 5.0.6 on 2025-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0008_remove_account_employee_employee_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accessible_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
