# Generated by Django 4.2 on 2025-05-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0007_purchaseorder_email_sent_and_more'),
        ('sia', '0009_alter_account_accessible_pages_alter_account_email_and_more'),
    ]

    operations = [
    ]
