# Generated by Django 4.2 on 2025-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0010_merge_20250520_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(help_text='Google OAuth Refresh Token', max_length=255, unique=True)),
                ('access_token', models.CharField(blank=True, help_text='Google OAuth Access Token (can be null, refresh token is primary)', max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Timestamp when the access token expires', null=True)),
                ('email_address', models.EmailField(help_text='The email address associated with these Google credentials', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google API Credential',
                'verbose_name_plural': 'Google API Credentials',
            },
        ),
    ]
